Solving-Our-Meals/ukki-back

- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
- src/main/resources/mappers/inquiry/inquiryMapper.xml
<br/>
#11 
<br/>
> 문의하기에 첨부파일 완료했습니다.
<br/>
> [FEATURE][Inquiry] 문의하기 첨부파일

- src/main/java/com/ohgiraffers/ukki/common/InquiryState.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryListDTO.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
- src/main/java/com/ohgiraffers/ukki/report/controller/ReportController.java
- src/main/java/com/ohgiraffers/ukki/report/model/dao/ReportMapper.java
- src/main/java/com/ohgiraffers/ukki/report/model/dto/ReportDTO.java
- src/main/java/com/ohgiraffers/ukki/report/model/dto/ReportListDTO.java
- src/main/java/com/ohgiraffers/ukki/report/model/service/ReportService.java
- src/main/resources/mappers/inquiry/inquiryMapper.xml
> 문의리스트를 구성할 때 필요한 값을 불러오는 API
<br/>
#14 
<br/>
> 
문의리스트를 구성하는 제목, 내용, 문의일자를 불러오는 API입니다. 마이페이지에서도 쓰시면 될 것 같아요
가게문의리스트를 뽑을 때 리뷰신고에 대한 내용도 필요해서 리뷰신고에 대한 기본 파일도 같이 올렸습니다.
<br/>
> [Feature][Inquiry] 문의리스트 API

- src/main/java/com/ohgiraffers/ukki/common/InquiryState.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryListDTO.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
- src/main/java/com/ohgiraffers/ukki/report/controller/ReportController.java
- src/main/java/com/ohgiraffers/ukki/report/model/dao/ReportMapper.java
- src/main/java/com/ohgiraffers/ukki/report/model/dto/ReportDTO.java
- src/main/java/com/ohgiraffers/ukki/report/model/dto/ReportListDTO.java
- src/main/java/com/ohgiraffers/ukki/report/model/service/ReportService.java
- src/main/resources/mappers/inquiry/inquiryMapper.xml
- src/main/resources/mappers/report/ReportMapper.xml
> 가게문의리스트에 필요한 리뷰신고리스트 API
<br/>
#17 
<br/>
> 
<br/>
> [FEATURE][Report] 리뷰신고 리스트

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 프로필 이미지 불러오기 구현
<br/>
#21 
<br/>
> 가게 상세페이지에서 프로필 이미지 불러오기 구현했습니다.
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 프로필 이미지 불러오기 구현

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
> 가게 상세페이지 메뉴 이미지 불러오기
<br/>
#26 
<br/>
> 아직 미완성입니다.
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 메뉴 이미지 불러오기(미완성)

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
> 가게 메뉴 이미지 불러오기 완료
#31 
<br/>
> 가게 메뉴 이미지 불러오기 완료했습니다.
<br/>
> [FEATURE][StoreDetail] 가게 메뉴 이미지 파일 불러오기 완료

- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
- src/main/resources/mappers/inquiry/inquiryMapper.xml
> 가게 문의 수정 및 삭제 API
<br/>
#15 
<br/>
> 
<br/>
> [FEATURE][Inquiry] 가게문의 수정 및 삭제

- build.gradle
- src/main/java/com/ohgiraffers/ukki/auth/Filter/JwtFilter.java
- src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthDAO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/AuthDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/JwtTokenDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/UserDetail.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
- src/main/resources/mappers/AuthMapper.xml
> 로그인은 구현완료입니다.
> 권한 다 넣어놓은 것 같은데 안들어가지면 말씀해주세요.
> 시큐리티랑 토큰은 아직 좀 부족한 것 같아요.
> 좀더 테스트해보고 확실하게 하겠습니다.
<br/>
#28 
<br/>
> 
<br/>
> [FEATURE][LoginAndSecurity]로그인 & 시큐리티

- src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/AuthDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
- src/main/resources/mappers/AuthMapper.xml
> 유저번호를 토큰에 담았습니다. 원래 토큰에 아이디랑 유저 역할만 담았는데 추가했어요.
> 문제있으면 연락주세요.
<br/>
#36 
<br/>
> 
<br/>
> [FIX][AddUserNo]유저번호 토큰에 저장

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/report/controller/ReportController.java
- src/main/java/com/ohgiraffers/ukki/report/model/dao/ReportMapper.java
- src/main/java/com/ohgiraffers/ukki/report/model/service/ReportService.java
- src/main/resources/mappers/report/ReportMapper.xml
> 가게 신고 수정 API, 삭제 API
<br/>
#18 
<br/>
> 
<br/>
> [FEATURE][Report] 가게 리뷰신고 수정 및 삭제

- src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
> 경고 문구 수정
<br/>
#42 
<br/>
> 
<br/>
> [FIX][SomeFix]경고 문구 수정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/controller/FindController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/FindMapper.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/FindDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/FindResponseDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/FindService.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
- src/main/resources/mappers/FindMapper.xml
> 아이디 찾기와 비밀번호 찾기 기능 구현
<br/>
#46 #47 
<br/>
> 
<br/>
> [FEATURE][FindAll]아이디 찾기와 비밀번호 찾기 기능 구현

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
>  가게 상세 페이지 리뷰 조회
<br/>
#54 
<br/>
>  가게 상세 페이지 리뷰 조회 
<br/>
> [FEATURE][StoreDetail] 가게 상세 페이지 리뷰 조회

- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
> null일 때 데이터 값을 0으로 넣었습니다.
<br/>
#61 
<br/>
> 
<br/>
> [FIX][ADMIN] 대시보드 무한로딩

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/ForJwtDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/CookieService.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/AuthMapper.xml
- src/main/resources/mappers/MypageMapper.xml
- src/main/resources/mappers/mypage/MypageMapper.xml
> claim에서 안담기던 문제를 해결했습니다.
<br/>
#65 
<br/>
> DTO쪽 관련 문제였는데 로직하나 추가해서 잘 나옵니다.
<br/>
> [FIX][FixJwtToken]JWT 토큰 문제 해결

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dto/ForJwtDTO.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/CookieService.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/AuthMapper.xml
- src/main/resources/mappers/MypageMapper.xml
- src/main/resources/mappers/mypage/MypageMapper.xml
> 토큰에 담긴 정보로 마이페이지 연결
<br/>
#68 
<br/>
> 더 추가할 예정입니다.
<br/>
프론트로 보내진 모습
> [FEATURE][ConnectMypageProfile]토큰에 담긴 정보로 마이페이지 연결

- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserActInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserResDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
- src/main/java/com/ohgiraffers/ukki/common/UserRole.java
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
- src/main/resources/mappers/admin/review/AdminReviewMapper.xml
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 관리자 회원에서 검색하는 것까지 API 만들었습니다.
<br/>
#66 
<br/>
> 현재 DB에 있는 userRole랑 enum에 있는 것 중에 DB의 BAD_USER과 enum의 BADUSER이 달라 충돌이 나서 일단 enum을 BAD_USER으로 바꿨습니다.
<br/>
> [FEATURE][ADMIN] 관리자 회원

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dto/ReservationStoreDTO.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dto/StoreBannerDTO.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/ReservationMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
- src/main/resources/mappers/reservation/ReservationMapper.xml
> 예약페이지 대표사진, 프로필 사진 구현
<br/>
#74 
<br/>
> 예약페이지 대표사진, 프로필 사진 구현
<br/>
> [FEATURE][RESERVATION] 예약페이지 대표사진, 프로필 사진 구현

- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MainDAO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MainDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MainService.java
- src/main/resources/mappers/MainMapper.xml
> 메인페이지 백 연결 중입니다
<br/>
#79
<br/>
> 
<br/>
> [FEATURE][Main] 메인페이지 백 연결

- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dto/ReservationInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/ReservationMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 예약 페이지 DB 저장
<br/>
#77 
<br/>
> 가게 예약 페이지 DB 저장하는데 레디스가 연결이 안되어서 제대로 작동하는지 확인 못했습니다.
<br/>
> [FEATURE][Reservation] 가게 예약 페이지 DB 저장

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/ReservationMapper.xml
> 캘린더 오늘 이전 날짜, 현시각 이전 클릭 방지
<br/>
#82 
<br/>
> 예약 시 db연결하는 로직 수정했습니다.
<br/>
> [FIX][reservation] 예약 DB 연결 수정

- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 관리자 측에서 회원 닉네임 수정, 삭제 API
<br/>
#66 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 회원 닉네임 수정, 삭제

- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 일반회원 정보만 가져오기
<br/>
#86 
<br/>
> 
<br/>
> [FIX][ADMIN] 회원 수정사항

- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreListDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/BannerDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/KeywordDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/OperationDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 가게조회 관련 API입니다.
<br/>
#88 
<br/>
> 현재 리스트와 검색은 완료했고 상세조회 하는중입니다.
<br/>
> [FEATURE][ADMIN] 가게 조회 API

- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 메인인 예약리스트 구현중입니다.
<br/>
#58 
<br/>
> 구현중입니다. 쿼리문 조금 손보면 될 것 같습니다.
<br/>
> [FEATURE][MypageReservation]마이페이지 메인 및 예약 리스트 구현중

- src/main/java/com/ohgiraffers/ukki/config/AppConfig.java
- src/main/java/com/ohgiraffers/ukki/config/MybatisConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/DirectionsRequest.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MainDTO.java
> 구현중
<br/>
#92
<br/>
> 
<br/>
> [FEATURE][MainMap] 메인페이지 현재 위치 기반 가게 최단 경로 찾기

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReservationInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 리뷰 정렬
<br/>
#94 
<br/>
> 가게 상세페이지 리뷰 정렬
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 리뷰 정렬

- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
> 데이터 넘어오는거 확인했고 처리하면 됩니다.
<br/>
#96 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 가게 정보 수정

- src/main/resources/mappers/mypage/MypageMapper.xml
> 리스트 제대로 나타납니다.
<br/>
#58 
<br/>
> 백엔드 쪽에서 정렬까지 해왔습니다.
> 예약쪽에서 예약 후 예약 시간이 지나면 만료로 넘어가는 백엔드는 현재 없습니다.
<br/>
> [FEATURE][MypageConnectAPI]마이페이지 예약 리스트 API연결

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 리뷰 제거 기능
<br/>
#100 
<br/>
> 
<br/>
> [FEATURE][MypageReview]마이페이지 리뷰 조회 기능

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/ReservationMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 리뷰 별점 / 리뷰 및 예약 시 유저 활동 업데이트
<br/>
#106 
<br/>
> 가게 상세페이지 리뷰 별점 / 리뷰 및 예약 시 유저 활동 업데이트
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 리뷰 별점 / 리뷰 및 예약 시 유저 활동 업데이트

- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
> 가게 수정 및 삭제 완료입니다.
<br/>
#96 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 가게 수정 삭제

- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreUserDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
> 가게등록 거의 다 했습니다.
<br/>
#111 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 가게 등록

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
> [FEATURE][Main] 메인페이지 백엔드

- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreUserDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 가게등록 및 총 회원 수
<br/>
#111 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 가게 등록 완료

- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ReservationListDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreUserDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 예약 리스트 조회
<br/>
#120 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 예약 리스트 조회

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
- src/main/resources/mappers/MainMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
<br/>
#122
<br/>
> 아직 구현중입니다
<br/>
> [FEATURE][SEARCH] 검색페이지 백 연결

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 리뷰 기본 이미지 구현
<br/>
#115 
<br/>
> 가게 상세페이지 리뷰 이미지 미업로드시 기본 이미지 구현
<br/>
> [FIX][StoreDetail] 가게 상세페이지 리뷰 기본 이미지 구현

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ChangedResNumInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/DayResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 예약 가능 인원에 따른 예약 버튼 활성화 여부
<br/>
#117 
<br/>
> 가게 상세페이지 예약 가능 인원에 따른 예약 버튼 활성화 여부 구현 중입니다.
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 예약 가능 인원에 따른 예약 버튼 활성화 여부

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 리뷰 삭제 
<br/>
#127 
<br/>
> 가게 상세페이지 리뷰 삭제 구현 중입니다.
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 리뷰 삭제 

- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ReservationInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
> 상세조회 및 삭제기능입니다. 상세조회만 하려고 했는데 삭제도 해버려서 같이 올렸습니다.
<br/>
#120 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 예약 상세조회 및 삭제

- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ReservationInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
- src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/dto/ReviewListDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
- src/main/resources/mappers/admin/review/AdminReviewMapper.xml
> 리뷰 리스트, 검색 완료입니다.
<br/>
#130 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 리뷰 조회

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
>마이페이지 문의 조회 기능
<br/>
#126 
<br/>
> 
<br/>
> [FEATURE][MypageSelectInquiry]마이페이지 문의 조회

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/SearchDTO.java
- src/main/resources/mappers/MainMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
> 기능 수정 중입니다
<br/>
#131
<br/>
> 
<br/>
> [FEATURE][SEARCH] 검색어 자동완성 및 실시간 인기 검색어 구현

- build.gradle
- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/entity/ExpiredReservationEntity.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/entity/ReservationEntity.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/repository/ExpiredReservationRepository.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/repository/ReservationRepository.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ExpiredReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 리뷰 삭제 완성
<br/>
#136 
<br/>
> 가게 상세페이지 리뷰 삭제 및 삭제 시 유저 활동 리뷰 -1
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 리뷰 삭제

- src/main/resources/mappers/MainMapper.xml
> 자동완성 및 실시간 인기 검색어 연결
<br/>
#142 
<br/>
> 
<br/>
> [FEATURE][SEARCH] 검색페이지 백

- src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/dto/ReviewInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/resources/mappers/admin/review/AdminReviewMapper.xml
> 리뷰상세조회
<br/>
#130 
<br/>
> 제가 삭제를 만들고 브런치를 여기로 올려버렸네요 삭제 쪽 이슈 닫아주시면 감사하겠습니다
<br/>
> [FEATURE][ADMIN] 리뷰 상세조회

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/UserController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 문의 수정 기능
<br/>
#139 
<br/>
> 
<br/>
> [FEATURE][MypageModifyInquiry]마이페이지 문의 수정

- src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
> 가게 수정 이미지 이름 변경, 가게 삭제 시 리뷰도 삭제 그리고 리뷰 삭제 시 이미지 지우는 것도 수정했습니다.
<br/>
#154 
<br/>
> 
<br/>
> [FIX][ADMIN] 가게 수정 이미지 이름 변경 , 가게 삭제 시 리뷰도 삭제

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 피드백 관련해서 변경했습니다.
<br/>
#153 
<br/>
> 형석씨가 말한 부분을 프론트에서 해결해놨는데 병합 후에 그게 안돼서 백도 변경했습니다.
> 이전에는 문제가 없었는데 병합할 때마다 달라지네요 ㅠㅠ
<br/>
> [FIX][FixMypageFeedback]마이페이지 피드백 관련사항 수정

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 프론트 쪽에서 만들어져 있던 상태여서 그 API에 연결했습니다.
<br/>
#140 
<br/>
> 문의 삭제 가능합니다.
> 모달까지 추가하고 첨부만 넣으면 문의 끝입니다.
<br/>
> [FEATURE][MypageDeleteInquiry]마이페이지 문의 삭제 로직 추가

- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/InquiryListDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
- src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/common/InquiryState.java
- src/main/java/com/ohgiraffers/ukki/common/handler/InquiryStateTypeHandler.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
> 문의 조회 만들고 있습니다.
<br/>
#156 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 문의 조회

- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
- src/main/resources/mappers/notice/NoticeMapper.xml
> 사용자/사장님 공지사항 백 연결
<br/>
#160 
<br/>
> 사용자/사장님 공지사항 상세조회 완료했습니다. 
<br/>
> [FEATURE][Notice] 사용자/사장님 공지사항 상세조회 백 연결

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 문의 파일 첨부 관련 로직으로 미완성입니다. 경로 및 파일 관리 때문에 변경될 수 있습니다.
<br/>
#141 
<br/>
> 
<br/>
> [FEATURE][MypageDownloadAndUpload]마이페이지 문의 파일 첨부 관련 로직

- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/resources/mappers/BossMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
> 주위 가게 8개 가져와서 룰렛 돌리고 현재시간에 가장 가까운 예약시간에 예약하는 로직 구현중
<br/>
#163
<br/>
> 가게 8개 찾아오고 시간대와 맞는 예약 찾기도 가능한데 아직 오류가 있어서 수정중입니다
<br/>
> [FEATURE][RANDOM] 랜덤 백 구현

- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
- src/main/resources/mappers/notice/NoticeMapper.xml
> 사용자 공지사항 검색 기능
<br/>
#165 
<br/>
> 사용자 공지사항 검색 기능 완료했습니다.
<br/>
> [FEATURE][Notice] 사장님 공지사항 검색 기능

- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
- src/main/resources/mappers/notice/NoticeMapper.xml
> 사장님 공지사항 검색 기능 수정
<br/>
#170 
<br/>
> 사장님 공지사항 검색 기능 수정
<br/>
> [FIX][BossNotice] 사장님 공지사항 검색 기능 수정

- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
- src/main/resources/mappers/notice/NoticeMapper.xml
> 가게 상세페이지 리뷰 삭제 시 드라이브 내 파일 삭제
<br/>
#172 
<br/>
> 가게 상세페이지 리뷰 삭제 시 드라이브 내 파일 삭제
<br/>
> [FIX][StoreDetail] 가게 상세페이지 리뷰 삭제 시 드라이브 내 파일 삭제

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageUpdateUserInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 프로필 정보
<br/>
#149 
<br/>
> 
<br/>
> [FEATURE][MypageProfileInfo]마이페이지 프로필 정보 로직

- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AnswerDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
> 문의 조회, 수정, 삭제
<br/>
#156 
<br/>
> 이슈는 조회만 만들었는데 수정이랑 삭제도 여기다가 구현해버렸습니다...
<br/>
> [FEATURE][ADMIN] 문의 조회, 수정, 삭제

- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AnswerDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
> 문의 첨부파일 다운로드
<br/>
#175 
<br/>
> 수정하면서 파일이름 때문에 기존의 문의하기와 수정에서도 파일이름 저장하는거 바꿨습니다.
<br/>
> [FIX][ADMIN] 문의 첨부파일

- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AnswerDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/model/dto/AdminNoticeCategoryDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/model/dto/AdminNoticeDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/model/service/AdminNoticeService.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
- src/main/resources/mappers/admin/notice/AdminNoticeMapper.xml
> 공지사항 리스트, 공지사항 검색, 공지사항 상세조회
<br/>
#177 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 공지사항 조회

- src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/model/service/AdminNoticeService.java
- src/main/resources/mappers/admin/notice/AdminNoticeMapper.xml
> 공지사항 생성, 수정, 삭제
<br/>
#180 
<br/>
> 
<br/>
> [FEATURE][ADMIN] 공지사항 생성, 수정, 삭제

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 프론트와 동일한 설명으로 이어야 하는 부분과 수정해야 할 각 부분을 알맞게 수정했습니다.
> 변경 코드 확인하시면 될 것 같습니다.
<br/>
#141 #185
<br/>
> 
<br/>
> [FEATURE][MypageInquiryFiles]마이페이지 문의 첨부 기능 추가, 마이페이지 리뷰 삭제 로직 추가

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 리뷰 상세 API 연결
<br/>
#187  
<br/>
> 리뷰 상세 조회 단일 연결용입니다.
<br/>
> [FEATURE][MypageReviewDetails]마이페이지 리뷰 상세 API 연결

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/ReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/AvailableSlotsDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/BossMapper.xml
> 사장님페이지 예약 현황, 에약인원 조정 백 연결중입니다
<br/>
#190
<br/>
> 
<br/>
> [FEATURE][BOSSPAGE] 사장님 페이지 백

- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
- src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/notice/NoticeMapper.xml
> 사장님 공지사항 최근 공지사항 조회
<br/>
#192 
<br/>
> 사장님 공지사항 최근 공지사항 조회
<br/>
> [FEATURE][BossNotice] 사장님 공지사항 최근 공지사항 조회

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 마이페이지 문의 수정 시 이전 파일 제거 로직 및 문의 첨부파일 다운로드 로직 추가
<br/>
#141 
<br/>
> 경로 바뀌거나 배포하면 주소는 수정해야 할 것 같습니다.
<br/>
> [FEATURE][MypageInquiryFiles]마이페이지 문의 수정 시 이전 파일 제거 로직 및 문의 첨부파일 다운로드 로직 추가

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 리뷰 디테일 부분에 DTO 내용 추가를 위함
<br/>
#196 
<br/>
> 마이페이지 리뷰 디테일 완성
<br/>
> [FEATURE][MypageReviewDetails]마이페이지 리뷰 디테일 완성

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/DetailReviewInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 사장님 페이지 리뷰 전체 조회 / 상세 조회
<br/>
#198 
<br/>
> 사장님 페이지 리뷰 전체 조회 / 상세 조회 완료했습니다.
<br/>
> [FEATURE][BossReview] 사장님 페이지 리뷰 전체 조회 / 상세 조회

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageProfileImageDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 프로필 이미지 업데이트 기능의 API를 설정하고 연결했습니다.
<br/>
#195 
<br/>
> 잘 저장되고 기존 업로드와 비슷하지만 나누어서 만들었습니다.
> 처음 로직엔 바로 dto쪽에서 get으로 꺼내서 경로를 찿아왔는데 이번엔 mapper 연결해서 가져왔습니다.
<br/>
> [FEATURE][MypageProfileImageUpdate]마이페이지 프로필 이미지 업데이트 기능

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageProfileImageDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 탈퇴만 되고 유저 정보랑 프로필 사진만 제거되는 상태입니다.
<br/>
#201 
<br/>
> 
<br/>
> [FEATURE][MypageDeleteAccount]마이페이지 탈퇴 기능 (미완성)

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageProfileImageDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/AuthMapper.xml
- src/main/resources/mappers/mypage/MypageMapper.xml
> 경로 설정에 따른 엔드포인트 설정
<br/>
#204
<br/>
> 
<br/>
> [FEATURE][AuthRole]Role에 따른 경로 설정 사전 준비

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/DetailReviewInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReportReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 가게 사장님 페이지 리뷰 신고
<br/>
#206 
<br/>
> 가게 사장님 페이지 리뷰 신고 기능 구현했습니다.
<br/>
> [FEATURE][BossReview] 가게 사장님 페이지 리뷰 신고

- Dockerfile
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/test/java/com/ohgiraffers/ukki/ApplicationTests.java
> 가게 수정 시 주소에서 오류나는 부분 해결했습니다.
<br/>
#208 
<br/>
> 프론트 쪽에서 보내는 값의 문제여서 수정했습니다. 그리고 docker만드려고 dockerfile만든 상태입니다.
<br/>
> [FIX][ADMIN] 가게 수정 주소 오류

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageProfileImageDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDetailDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/AuthMapper.xml
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 예약 상세
<br/>
#203 
<br/>
> 마이페이지 예약 상세페이지입니다.
<br/>
> [FEATURE][MypageReservationDetail]예약 상세

- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/ReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
<br/>
#210
<br/>
> 구현중입니다
<br/>
> [FEATURE][BOSSPAGE] 사장님페이지 인원 조정 백

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 사장님 페이지 리뷰 신고 시 리뷰 신고 횟수 수정
<br/>
#215 
<br/>
> 사장님 페이지 리뷰 신고 시 리뷰 신고 횟수 증가하도록 로직 구현했습니다.
<br/>
> [FEATURE][BossReview] 사장님 페이지 리뷰 신고 시 리뷰 신고 횟수 수정

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
- src/main/resources/mappers/ReservationMapper.xml
> 예약 시 DB 유저 활동 테이블에 유저 정보 없으면 INSERT하고 있으면 UPDATE하기
<br/>
#218 
<br/>
> user2로 로그인하고 에약했을 때 수정 안됐던 이유가 해당 테이블에 update만 하는 로직을 구현했기 때문에 안되었습니다. 그래서 예약 시 DB 유저 활동 테이블에 유저 정보 없으면 INSERT하고 있으면 UPDATE하는 로직으로 수정했습니다.
<br/>
> [FIX][Reservation] 예약 시 유저 활동 데이터 로직 수정

- .dockerignore
- .github/workflows/deploy.yml
- Dockerfile
- build.gradle
- deploy.sh
- docker-compose.yml
- src/main/resources/application-prod.yml
> github action설정과 사진경로 옮기기, dockerignore및 배포를 위한 설계
#220 
<br/>
> build.gradle에서 springboot 버전이 현재 정식 출시 버전이 아니라 에러가 나서 변경했습니다. 혹시 오류나시면 말씀해주세요
<br/>
> [FEATURE][DEPLOY] 배포설정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageDeleteAccount.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> [FEATURE][MypageSearch]마이페이지 검색기능

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/InquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
- src/main/resources/mappers/ReservationMapper.xml
> 사장님 페이지 문의 내역 전체 조회
<br/>
#224 
<br/>
> 사장님 페이지 문의 내역 전체 조회 구현 완료했습니다. 근데 정렬도 넣을지 고민 중이에요.
<br/>
> [FEATURE][BossIquiry] 사장님 페이지 문의 내역 전체 조회

- src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
<br/>
#226
<br/>
> 인원 조정만 좀 더 다듬으면 될거같습니다 미완성입니다
<br/>
> [FEATURE][bossPage] 사장님 페이지 예약 날짜및 인원 조회

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 사장님 페이지 문의 내역 상세 조회
<br/>
#228 
<br/>
> 사장님 페이지 문의 내역 상세 조회 구현했는데 파일 다운로드도 구현했습니다.
<br/>
> [FEATURE][BossInquiry] 사장님 페이지 문의 내역 상세 조회

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 사장님 페이지 문의 내역 삭제
<br/>
#230 
<br/>
> 사장님 페이지 문의 내역 삭제 구현했습니다. 파일 삭제도 했습니다.
<br/>
> [FEATURE][BossInquiry] 사장님 페이지 문의 내역 삭제

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 예약리스트, 리뷰의 경우 가게 이름으로 검색하고, 문의의 경우 문의 제목으로 검색입니다.
<br/>
#233 
<br/>
> 어제 안된건 매퍼를 올리지 않아서 안된 것 같습니다.
> 그리고 문의 삭제할 때 파일 삭제하는 로직이 없어서 추가했어요.
<br/>
> [FEATURE][MypageSearch]마이페이지 검색 기능 완료 & 문의 파일 삭제 로직 추가

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 사장님 페이지 문의 수정
<br/>
#239 
<br/>
> 사장님 페이지 문의 수정 구현 완료했습니다.
내용 수정 / 드라이브 파일 수정 완료했습니다. 
파일 수정은 다음 3가지 모두 다 완료했습니다.
- 파일 변경 시 기존 파일 삭제 & 새로운 파일 저장
- 기존 파일만 삭제
- 기존 파일 없을 때 새로운 파일 추가
<br/>
> [FEATURE][BossInquiry] 사장님 페이지 문의 수정

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 버튼 조건부 렌더링
<br/>
#235 
<br/>
> 마이페이지 조건부 렌더링을 위해 DTO 및 Mapper 수정
<br/>
> [FEATURE][MypageReservationConditionalRendering]마이페이지 버튼 조건부 렌더링

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/DayResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/ReservationRepository.java
- src/main/resources/mappers/BossMapper.xml
> 시간별 인원 조정
<br/>
#242
<br/>
> 
<br/>
> [FEATURE][BOSS] 사장님페이지 시간별 인원 조정

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 문의 파일명 저장 통일
<br/>
#245 
<br/>
> 
<br/>
> [FIX][FixSaveFilesName]문의 파일명 저장 통일 및 문의 삭제 시 파일 제거 로직 추가

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/ReservationMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
>  가게 상세페이지 예약 중복 막기 및 그 외 수정 사항
<br/>
#247 
<br/>
>  가게 상세페이지 예약 중복 막기 및 그 외 수정 사항 수정 및 구현했습니다.
- 가게 상세페이지 예약 중복 막기 
-  사장님 페이지 문의 내역에서 최근 문의내역 선택 시 상세보기 
-  가게 상세페이지 리뷰 별점 높은 순 / 낮은 순 추가
<br/>
> [FIX][StoreDetail, BossInquiry] 예약 중복 막기 및 그 외 수정사항

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationQRDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 예약 취소
<br/>
#236 
<br/>
> 
<br/>
> [FEATURE][MypageDeleteReservation]마이페이지 예약 취소

- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 예약 취소 시 해당 QR 제거
<br/>
#238 
<br/>
> 
<br/>
> [FEATURE][DeleteReservationQR]예약 취소 시 해당 QR 제거

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationQRDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 예약 삭제 후 UserAct 카운트
<br/>
#251 
<br/>
> 예약 삭제 후 UserAct의 예약 수가 카운트 집계되는 것입니다.
> 현재 기준 삭제는 반영되지만 userProfile쪽에서는 새로고침해야 집계되어 프론트 점검해야할 것 같습니다.
<br/>
> [FEATURE][CountUserActForDeleteReservation]예약 삭제 후 UserAct 카운트

- src/main/java/com/ohgiraffers/ukki/exception/GlobalExceptionHandler.java
- src/main/java/com/ohgiraffers/ukki/exception/WebErrorController.java
- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
- src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/DayResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/BossMapper.xml
- src/main/resources/mappers/ReservationMapper.xml
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 예약 만료 시 예약 버튼 비활성화 버그 해결
<br/>
#407 
<br/>
> 가게 상세페이지 예약 만료 시 예약 버튼 비활성화 버그 해결했습니다.
<br/>
> [FIX][StoreDetail] 가게 상세페이지 예약 만료 시 예약 버튼 비활성화 버그 해결

- .gitignore
- build.gradle
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/InquiryInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
- src/main/java/com/ohgiraffers/ukki/config/GoogleDriveConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryDTO.java
> 구글 드라이브 연동
<br/>
#258 
<br/>
> 구글 드라이브 연동했습니다. 사용법은 내일 학원에서 알려드리겠습니다!
<br/>
> [FEATURE][DRIVE] 구글 드라이브 연동

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
> LocalDate의 직렬화 문제때문에 수정했습니다.
<br/>
#260 
<br/>
> 
<br/>
> [FIX][WEB] LocalDate 직렬화 문제

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 오류 수정
<br/>
#262
<br/>
> 
<br/>
> [FIX][BOSS] 사장님페이지 수정

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/DetailReviewInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/InquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/OperationDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
> 사장님 페이지, 가게 상세페이지 오류 해결
<br/>
#264 
<br/>
> 사장님 페이지, 가게 상세페이지 오류 해결
<br/>
> [FIX][Total] 사장님 페이지, 가게 상세페이지 오류 해결

- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDetailDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/UserDTO.java
- src/main/resources/mappers/StoreDetailMapper.xml
> DTO date, time 스트링화
<br/>
#266 
<br/>
> 
<br/>
> [FIX][FixForServer]서버 배포를 위한 수정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/controller/FindController.java
- src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
- src/main/java/com/ohgiraffers/ukki/config/GoogleDriveConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 서버 배포 수정
<br/>
#268 
<br/>
> 
<br/>
> [FIX][FixForServerDeployment]서버 배포 수정

- .dockerignore
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
- src/main/resources/mappers/BossMapper.xml
> [FIX][ALL] 서버 배포용 수정

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
> 서버 배포용 수정
<br/>
#273 
<br/>
> 서버 배포용 수정
<br/>
> [FIX][Total] 서버 배포용 수정

- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
> URL수정
<br/>
#271 
<br/>
> 
<br/>
> [FIX][URL] 배포용 수정

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
> 가게 상세페이지 리뷰 작성 버그
<br/>
#279 
<br/>
> 가게 상세페이지 리뷰 작성 버그 수정 중입니다.
<br/>
> [FIX][StoreDetail] 가게 상세페이지 리뷰 작성 버그

- .github/workflows/deploy.yml
> GitHub Action 사용을 위한 deploy 수정
<br/>
#281 
<br/>
> 
<br/>
> [FIX][DEPLOY] Deploy 수정

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> [FIX][BOSS] 예약가능인원 수정

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/exception/GlobalExceptionHandler.java
- src/main/java/com/ohgiraffers/ukki/exception/WebErrorController.java
- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/ReservationMapper.xml
> 에러 페이지 설정
<br/>
#288 
<br/>
> 에러 페이지 설정 중입니다. 계속 에러가 뜨네요... 에러 페이지 연결하면 무한 루프뜨거나 아님 데이터는 잘 가져오는데 에러페이지가 렌더링 되거나 계속 오류가 나서 수정 중입니다.
<br/>
> [FEATURE][Exception] 에러 페이지 설정

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/exception/GlobalExceptionHandler.java
- src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 가게 상세페이지 예약 가능 인원 조회 버그
<br/>
#290 
<br/>
>  가게 상세페이지 예약 가능 인원 조회 버그
<br/>
> [FIX][StoreDetail] 가게 상세페이지 예약 가능 인원 조회 버그

- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/common/Controller/GoogleDriveController.java
- src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 구글 드라이브 연결입니다.
<br/>
#287 
<br/>
> 
<br/>
> [FEATURE][UploadImageAndSelectImageConnectGoogleDrive]구글 드라이브 업로드와 이미지 보이기

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
- src/main/resources/mappers/AuthMapper.xml
- src/main/resources/mappers/SignupMapper.xml
> 구글 드라이브 문의 연결
<br/>
#295 #302 
<br/>
> 
<br/>
> [FEATURE][ConnectGoogleDrive]구글 드라이브 문의 수정, 삭제, 회원 탈퇴 연결

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/BossMapper.xml
> 가게 상세페이지 이미지 드라이브 연결
<br/>
#297 
<br/>
> 가게 상세페이지 이미지 드라이브 연결
<br/>
> [FEATURE][StoreDetail] 가게 상세페이지 이미지 드라이브 연결

- build.gradle
- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
- src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
- src/main/resources/mappers/qr/QrMapper.xml
> 이미지 경로 변환
<br/>
#299 
<br/>
> 
<br/>
> [FIX][ADMIN] 이미지 경로 변환

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/BossMapper.xml
> 사장님 페이지 문의 파일 버그 해결
<br/>
#308 
<br/>
> 사장님 페이지 문의 파일 버그 해결했습니다. 다른 파일 수정은 잘 되는데 텍스트만 수정할 때 기존 파일이 삭제되는 오류가 있어 수정했습니다.
<br/>
> [FIX][BossInquiry] 사장님 페이지 문의 파일 버그 해결

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> [FIX][GRAPH] 이번주 예약 그래프

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
> [][]메인 업데이트 URL 누락 수정

- build.gradle
- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/common/Controller/GoogleDriveController.java
- src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 문제있는 부분 하나씩 수정했습니다.
<br/>
#
<br/>
> 
<br/>
> [FIX][FixComplement]문제있는 부분 수정

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/resources/mappers/StoreDetailMapper.xml
> 리뷰 작성 권한 오류
<br/>
#321 
<br/>
> 리뷰 작성 권한 오류 
<br/>
> [FIX][StoreDetail] 리뷰 작성 권한 오류

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/NoReviewReservListDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
- src/main/resources/mappers/StoreDetailMapper.xml
>  리뷰 작성 시 예약 번호 선택
<br/>
#323 
<br/>
>  리뷰 작성 시 예약 번호 선택
<br/>
> [FEATURE][StoreDetail] 리뷰 작성 시 예약 번호 선택

- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
> 메인페이지 수정
<br/>
#325
<br/>
> 
<br/>
> [FIX][MAIN] 메인페이지 수정

- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
> 환경 변수 수정
<br/>
#330 
<br/>
> 
<br/>
> [CHORE][EnvironmentVariable]환경 변수 수정

- src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
> 구글 드라이브 환경 설정 수정
<br/>
#332 
<br/>
> 구글 드라이브 환경 설정 수정
<br/>
> [FIX][Total] 구글 드라이브 환경 설정 수정

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageUpdateUserInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 수정 문제 해결
<br/>
#334 
<br/>
> 
<br/>
> [FIX][FixMypageInquiry]마이페이지 문의 버그 수정

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageUpdateUserInfoDTO.java
- src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
- src/main/resources/mappers/mypage/MypageMapper.xml
> 마이페이지 유저 정보 수정 버그 해결
<br/>
#334 
<br/>
> 
<br/>
> [FIX][FixMypageModifyUserInfo]마이페이지 유저 정보 수정 버그 해결

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 에러 해결했습니다
<br/>
#339
<br/>
> 
<br/>
> [FIX][BOSSPAGE] 사장님페이지 오류 해결

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/resources/application-prod.yml
> 인스턴스 업그레이드에 따른 URL update
<br/>
#337 
<br/>
> 
<br/>
> [FIX][URL] URL 수정

- src/main/java/com/ohgiraffers/ukki/config/HealthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
- src/main/resources/application-prod.yml
> 도메인으로 url 변경 완료
<br/>
#342 
<br/>
> 
<br/>
> [FIX][WEB] 도메인으로 url 변경

- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/DayTimeDTO.java
- src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
- src/main/java/com/ohgiraffers/ukki/config/HealthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
- src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
- src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
- src/main/resources/application-prod.yml
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
- src/main/resources/mappers/qr/QrMapper.xml
> qr체크인 수정 및 관리자 쪽 수정
<br/>
#346
<br/>
> 
<br/>
> [FIX][QR] qr체크인 수정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/auth/model/service/UserDetail.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
> https에서만 사용 가능해지게 변경하는 설정으로 최종 배포 후 사용해야 합니다.
<br/>
#344 
<br/>
> 시큐리티 설정은 좀 만져봤는데 문제가 많이 생길 것 같아서 현재설정해놓은 json token 보안만두고 가장 기본만 둘지 서로 성의해봐야 될 것 같습니다.
> 생각보다 예외 상황이 많습니다.
<br/>
> [FIX][SecuritySettings]CookieSecure false에서 true로 변경

- src/main/resources/mappers/BossMapper.xml
> 에약 그래프에서 자꾸 에러가 발생하네요
<br/>
#357
<br/>
> 
<br/>
> [FIX][WEEK] 예약 그래프

- .github/workflows/cd.yml
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
- src/main/resources/mappers/qr/QrMapper.xml
> 관리자쪽에 기능 개선했습니다. - qr, 문의 리스트, 문의 상세에서 문의자 정보 등
<br/>
#355 
<br/>
> 
<br/>
> [FIX][ADMIN] 관리자 기능 개선

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
- src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
- src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
- src/main/resources/mappers/BossMapper.xml
- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
- src/main/resources/mappers/qr/QrMapper.xml
> [Merge][ForUpdate] 우끼 업데이트

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
> 로그아웃 수정
<br/>
#361 
<br/>
> 
<br/>
> [FIX][FixLogout]로그아웃 수정

- src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
- src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
- src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
- src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
- src/main/resources/mappers/BossMapper.xml
> 그래프 구현 완료
<br/>
#360 
<br/>
> 
<br/>
> [FIX][BOSS] 사장님 페이지 그래프 구현

- src/main/resources/mappers/notice/NoticeMapper.xml
> 전반적인 오류 수정
<br/>
#364 
<br/>
> 전반적인 오류 수정
<br/>
> [FIX][Total] 전반적인 오류 수정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
> 문제해결 테스트
<br/>
#361 
<br/>
> 
<br/>
> [FIX][FixLogout]로그아웃 문제 해결용

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
> 배포 시 로그아웃 문제 수정을 위함
<br/>
#361 
<br/>
> 
<br/>
> [FIX][FixLogout]배포 시 로그아웃 문제

- src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
- src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
- src/main/resources/mappers/admin/review/AdminReviewMapper.xml
- src/main/resources/mappers/admin/store/AdminStoreMapper.xml
- src/main/resources/mappers/admin/user/AdminUserMapper.xml
> 기능에 영향은 없지만 약간의 오타가 있어서 수정했습니다.
<br/>
#371 
<br/>
> 
<br/>
> [FIX][ADMIN] 약간의 수정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
> [MERGE][ForUpdate]우끼 업데이트

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
> [FIX][FixLogout]로그아웃 고치기

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
> 서버 로그아웃 문제
<br/>
#373
<br/>
> 
<br/>
> [FIX][FixLogoutForServer]서버 로그아웃 문제

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
> 시큐리티 컨픽에 있는 로그아웃 부 때문에 /auth/logout 요청으로 가더라도 시큐리티 컨픽 로그아웃으로 걸리는 문제였습니다.
> 제거 후에 제가 만든 로그아웃으로 정상 작동합니다.
> 기존 로컬에서는 시큐리티 컨픽에서 간단하게 쿠키에 있는 auth와 refresh를 삭제해도 문제없었으나 배포하면서 문제생긴것 같습니다. sout가 왜 안찍히나 확인하다가 이게 문제라는 점을 알았습니다.
<br/>
#387 
<br/>
> 
<br/>
> [FIX][FixLogout]로그아웃 완료

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
> 로그아웃 수정
<br/>
#387 
<br/>
> 
<br/>
> [FIX][FixLogoutServer]로그아웃 수정

- src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
> [][]우끼 업데이트

- src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
> [][]로그아웃 수정
